name: Main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 4 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"